### ISSUE TITLE
feature:install jax-rs-provider-swagger throws Error

### ISSUE THREAD

**Issue by coverxiaoeye** [hstaudacher/osgi-jax-rs-connector#124] opened 2015-11-19 00:59 UTC
when i try to install  jax-rs-provider-swagger feature in apache-karaf-3.0.5, it throws error!  It seems that com.eclipsesource.jaxrs:provider-swagger:jar:1.0 can not be downloaded from central maven repo.

Here is the error info:
karaf@root()> feature:install jax-rs-provider-swagger 1.0
Error executing command: Can't install feature jax-rs-provider-swagger/0.0.0:
Error resolving artifact com.eclipsesource.jaxrs:provider-swagger:jar:1.0: Could not transfer artifact com.eclipsesource.jaxrs:provider-swagger:jar:1.0 from/to central (http://repo1.maven.org/maven2/): repo1.maven.org

**Comment by hstaudacher** [comment] 2015-11-30 16:07
I think this is a duplicate of #125. Closed.

**Closed by hstaudacher** 2015-11-30 16:07 UTC
Labels: bug
