### ISSUE TITLE
swagger-all imports

### ISSUE THREAD

**Issue by maggu2810** [hstaudacher/osgi-jax-rs-connector#129] opened 2015-12-03 16:51 UTC
Hello,
for your swagger-all bundle you are not importing javax.xml stuff.
https://github.com/hstaudacher/osgi-jax-rs-connector/blob/5.2.0/build/com.eclipsesource.jaxrs.swagger.all/pom.xml#L57

Is there any reason for you to remove this imports?

```text
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/annotation/XmlRootElement
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:212)
        at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:159)
        at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:99)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:138)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:103)
        at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:119)
        at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:103)
        at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:79)
        at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
        at io.swagger.jaxrs.Reader.parseMethod(Reader.java:742)
        at io.swagger.jaxrs.Reader.read(Reader.java:269)
        at io.swagger.jaxrs.Reader.read(Reader.java:170)
        at io.swagger.jaxrs.Reader.read(Reader.java:147)
        at io.swagger.jaxrs.listing.ApiListingResource.scan(ApiListingResource.java:64)
        at io.swagger.jaxrs.listing.ApiListingResource.process(ApiListingResource.java:90)
        at io.swagger.jaxrs.listing.ApiListingResource.getListingJson(ApiListingResource.java:129)
        at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_66]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_66]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_66]
        at java.lang.reflect.Method.invoke(Method.java:497)[:1.8.0_66]
        at org.glassfish.jersey.server.model.internal.ResourceMethodInvocationHandlerFactory$1.invoke(ResourceMethodInvocationHandlerFactory.java:81)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher$1.run(AbstractJavaResourceMethodDispatcher.java:144)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.invoke(AbstractJavaResourceMethodDispatcher.java:161)
        at org.glassfish.jersey.server.model.internal.JavaResourceMethodDispatcherProvider$ResponseOutInvoker.doDispatch(JavaResourceMethodDispatcherProvider.java:160)
        at org.glassfish.jersey.server.model.internal.AbstractJavaResourceMethodDispatcher.dispatch(AbstractJavaResourceMethodDispatcher.java:99)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:389)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:347)
        at org.glassfish.jersey.server.model.ResourceMethodInvoker.apply(ResourceMethodInvoker.java:102)
        at org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:326)[10:com.eclipsesource.jaxrs.jersey-min:2.22.1]
        ... 35 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.annotation.XmlRootElement cannot be found by com.eclipsesource.jaxrs.swagger-all_1.5.4
        at org.eclipse.osgi.internal.loader.BundleLoader.findClassInternal(BundleLoader.java:432)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:345)
        at org.eclipse.osgi.internal.loader.BundleLoader.findClass(BundleLoader.java:337)
        at org.eclipse.osgi.internal.loader.ModuleClassLoader.loadClass(ModuleClassLoader.java:160)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)[:1.8.0_66]
        ... 66 more
```

**Comment by hstaudacher** [comment] 2015-12-04 14:13
Duplicate of #123

**Closed by hstaudacher** 2015-12-04 14:13 UTC
